name: Prepare for release

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Add execution plugin
        run: npm install @semantic-release/exec
      - name: Release to GitHub
        env:
          # We use a different token here in order to make the release as
          # a robot github user - that way Github Actions triggers on that
          # release (which it wouldn't if we used just GITHUB_TOKEN).
          GITHUB_TOKEN: ${{ secrets.RELEASER_GITHUB_TOKEN }}
        run: npx semantic-release
