name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compute manifest
        id: manifest
        run: |
          echo -n "::set-output name=manifest::"
          # Assume that we are on a tag named vX.Y.Z
          cat manifest.json | sed "s/__VERSION__/${GITHUB_REF##*/v}/" | jq -c .

      - name: Compute Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/kamelnetworks/sonic_exporter
          tags: |
            type=schedule
            type=ref,event=tag
            type=sha
          labels: |
            com.azure.sonic.manifest=${{ steps.manifest.outputs.manifest }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
